schoolapp/urls.py
from django.urls import path
from .views import *
# from schoolapp import views

app_name = 'schoolapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),


    # Grade Detail
    path('grade/<int:pk>/gradedetail/',
         GradeDetailView.as_view(), name='gradedetail'),

    # Student Detail
    path('grade/<int:g_id>/student/<int:pk>/studentdetail/',
         StudentDetailView.as_view(), name='studentdetail'),

    # Class Teachers List
    path('classteacherslist/', ClassTeachersListView.as_view(),
         name='classteacherslist'),



    # Adding Data

    # Add Class Teacher
    path('addclassteacher/',
         AddClassTeacherView.as_view(), name='addclassteacher'),

    # Add Grades
    path('addgrades/',
         AddGradesView.as_view(), name='addgrades'),

    # Add Students
    path('grade/<int:g_id>/addstudents/',
         AddStudentsView.as_view(), name='addstudents'),

    # Add Sujects
    path('grade/<int:g_id>/addsubjects/',
         AddSubjectsView.as_view(), name='addsubjects'),

    # Generate StudentDetail Pdf
    path('studentdetail/generatepdf',
         GeneratePdfView.as_view(),
         name='generatepdf'),

]

schoolproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls', namespace='schoolapp')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/addclassteacher.html
<div class="mx-5 py-5 px-5">
	<form class="form-group" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		{% if errors %}
		<div class="alert alert-danger">
			{{errors}}
		</div>
		{% endif %}
		<br>
		<button class="w-100 btn btn-primary">Add classteacher</button>
	</form>
</div>

templates/addgrades.html
<div class="mx-5 py-5 px-5">
	<form class="form-group" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		{% if errors %}
		<div class="alert alert-danger">
			{{errors}}
		</div>
		{% endif %}
		<br>
		<button class="w-100 btn btn-primary">Add Grade</button>
	</form>
</div>

templates/addstudents.html
<div class="mx-5 py-5 px-5">
	<form class="form-group" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		{% if errors %}
		<div class="alert alert-danger">
			{{errors}}
		</div>
		{% endif %}
		<br>
		<button class="w-100 btn btn-primary">Add Student</button>
	</form>
</div>

templates/addsubjects.html
<div class="mx-5 py-5 px-5">
	<form class="form-group" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		{% if errors %}
		<div class="alert alert-danger">
			{{errors}}
		</div>
		{% endif %}
		<br>
		<button class="w-100 btn btn-primary">Add Subject</button>
	</form>
</div>

templates/base.html
{% load static %}


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"> -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title>School App</title>
</head>
<body>

	<!-- Top Navigation Bar -->
	<nav style="box-shadow: 0 0 1px 3px grey;" class="navbar navbar-expand-lg navbar-dark bg-dark text-light fixed-top">
	  {% if request.user.is_anonymous %}
	  	<a class="navbar-brand" href="{% url 'schoolapp:login' %}">School App</a>
	  {% endif %}
	  	
	  {% if request.user.is_authenticated %}
	  <a class="navbar-brand" href="{% url 'schoolapp:home' %}">School App</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	  	<span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    	<div class="ml-auto text-center">Logged in as: {{request.user.username}}</div>
	    	<div class="ml-auto">
				<a class="nav-link btn btn-danger" href="{% url 'schoolapp:logout' %}">Logout</a>
	    	</div>
	    	{% endif %}
	  	</div>
	</nav>

	
	<!-- Header -->
	<header style="margin-top: 60px;">
	{% block header %}

	{% endblock %}
	</header>

	<!-- Content -->
	<div style="" class="container-fluid px-0 mx-0">
		<div style="height: inherit;" class="container-fluid row px-0 mx-0">
		{% if request.user.is_authenticated %}
			<div class="col-xs-12 col-sm-2 container-fluid sidenav">
		{% else %}
			<div class="col-xs-12 col-sm-2 container-fluid">
		{% endif %}
			<input type=button class="w-100 btn btn-secondary bg-dark" value="Back" onClick="javascript:history.go(-1);">
			{% block sidemenu %}

			{% endblock %}
			</div>
			

			<div class="col-xs-12 col-sm-7 container-fluid py-sm-1 mx-sm-0">
			{% block content %}

			{% endblock %}
			</div>


			<div class="col-xs-12 col-sm-3 container-fluid py-sm-1 mx-0">
			{% block rightsidebar %}

			{% endblock %}
			</div>
		</div>
	</div>



	<footer class="mt-2 mb-0">
	{% block footer %}
	{% endblock %}
	</footer>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<!-- <script type="text/javascript" href="{% static 'js/jquey.min.js' "></script>
	<script type="text/javascript" href="{% static 'js/bootstrap.min.js' "></script> -->
</body>
</html>

templates/classteacherslist.html
{% extends 'base.html' %}




{% block header %}
	<div class="h1 py-3 bg-dark text-light text-center">Class Teachers List Header</div>
{% endblock %}




{% block sidemenu %}
<div class="h4">Menu</div>
<a href="{% url 'schoolapp:home' %}">Grades</a>
<a href="{% url 'schoolapp:classteacherslist' %}">Teachers</a>
{% endblock %}




{% block content %}
<div>
	<div class="h4 my-3 py-2 mx-auto text-center bg-info">Class Teacher Details</div>
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<th>ID</th>
			<th>Name</th>
			<th>Grade</th>
		</thead>
		<tbody>
			{% for teacher in classteacherslist %}
			<tr>
				<td>{{teacher.id}}</td>
				<td>{{teacher.name}}</td>
				<td>{{teacher.grade}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}




{% block footer %}
	<div class="h1 mb-0 py-2 bg-dark text-light text-center">Class Teachers List Footer</div>
{% endblock %}

templates/gradedetail.html
{% extends 'base.html' %}
<!-- {% load static %} -->



{% block header %}
	<div class="block-header h1 py-3 bg-dark text-light text-center">Class Detail Header</div>
{% endblock %}




{% block sidemenu %}
<div class="h4">Menu</div>
<a href="{% url 'schoolapp:home' %}">Grades</a>
<a href="{% url 'schoolapp:classteacherslist' %}">Teachers</a>
{% endblock %}




{% block content %}
<!-- Studentslist Table -->
<div>
	<div class="h4 py-2 text-center bg-info">
		<div class="px-sm-5 py-sm-2 d-inline-block">Class-{{selectedgrade.grade}}</div> 
		<div class="px-sm-5 py-sm-2 d-inline-block">Class Teacher: {{selectedgrade.class_teacher}}</div>
	</div>
	
	<div class="h4 py-2 mx-auto text-center bg-info">
	Students</div>
	<table class="table table-striped table-bordered table-hover text-center">
		<thead>
			<th>S.N.</th>
			<th>Student ID</th>
			<th>Name</th>
			<th>View Student Info</th>
		</thead>
		<tbody>
			{% for student in selectedgrade.students.all %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{student.id}}</td>
				<td>{{student.name}}</td>
				<td><a href="{% url 'schoolapp:studentdetail' selectedgrade.id student.id %}">Click here</a></td>
			</tr>					
			{% endfor %}
		</tbody>
	</table>
</div>

{% endblock %}



{% block rightsidebar %}
<div class="h4 py-2 mx-auto text-center bg-info">
	Subjects</div>
<table class="table table-striped table-bordered">
	<thead>
		<th>Id</th>
		<th>Title</th>
	</thead>
	<tbody>
		{% for subject in selectedgrade.subjects.all %}
		<tr>
			<td>{{subject.id}}</td>
			<td>{{subject.title}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<div class="d-block">
  	<a class="d-block btn btn-secondary my-1" href="{% url 'schoolapp:addstudents' selectedgrade.id %}">Add Students</a>
  	<a class="d-block btn btn-secondary my-1" href="{% url 'schoolapp:addsubjects' selectedgrade.id %}">Add Subjects</a>
</div>
{% endblock %}




{% block footer %}
	<div class="h1 mb-0 py-2 bg-dark text-light text-center">Class Detail Footer</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}




{% block header %}
	<div class="block-header h1 py-3 bg-dark text-light text-center">Home Page</div>
{% endblock %}




{% block sidemenu %}
<div class="h4">Menu</div>
<a href="{% url 'schoolapp:home' %}">Grades</a>
<a href="{% url 'schoolapp:classteacherslist' %}">Teachers</a>
{% endblock %}




{% block content %}
<div class="h4 my-3 py-2 mx-auto text-center bg-info">Select Grade</div>
<nav aria-label="breadcrumb">
  	<ol class="breadcrumb">
  		{% for grade in allgrades %}
		<li class="breadcrumb-item">
			<a href="{% url 'schoolapp:gradedetail' grade.id %}">{{grade.grade}}</a>
		</li>
		{% endfor %}
  	</ol>
</nav>
<div class="container">
</div>
{% endblock %}




{% block rightsidebar %}
<div class="">
  	<a class="d-block btn btn-secondary border border-dark" href="{% url 'schoolapp:addclassteacher' %}">Add Class Teachers</a>
  	<a class="d-block btn btn-secondary border border-dark" href="{% url 'schoolapp:addgrades' %}">Add Grades</a>
</div>
{% endblock %}




{% block footer %}
	<div class="h1 py-2 bg-dark text-light text-center fixed-bottom">Home Footer</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}



{% block header %}
<div class="block-header h1 py-5 text-center bg-info text-light">School Management System</div>
{% endblock %}




{% block sidemenu %}

{% endblock %}




{% block content %}
<div class="justify-content-center py-5 px-0">
	<form class="form-group" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		{% if request.GET.next %}
		<input type="hidden" name="next" value="{{request.GET.next}}">
		{% endif %}
		{% if errors %}
		<div class="alert alert-danger">
			{{errors}}
		</div>
		{% endif %}
		<br>
		<button class="w-100 btn btn-primary">Login</button>
	</form>
</div>
{% endblock %}




{% block footer %}
<div class="h1 py-2 bg-dark text-light text-center">Login Footer</div>
{% endblock %}

templates/studentdetail.html
{% extends 'base.html' %}




{% block header %}
	<div class="block-header h1 py-3 bg-dark text-light text-center">Student Detail Header</div>
{% endblock %}




{% block sidemenu %}
<div class="h4">Menu</div>
<a href="{% url 'schoolapp:home' %}">Grades</a>
<a href="{% url 'schoolapp:classteacherslist' %}">Teachers</a>
{% endblock %}




{% block content %}
<div class="container-fluid">
	<table class="table responsive table-striped table-bordered table-hover">
		<div class="h4 py-2 mx-auto text-center bg-info">
		Details</div>
		<thead>
			<th>Student Id</th>
			<th>Student Name</th>
			<th>Grade</th>
			<th>Class Teacher</th>
		</thead>
		<tbody>
			<tr>
				<td>{{student.id}}</td>
				<td>{{student.name}}</td>
				<td>{{student.grade}}</td>
				<td>{{student.grade.class_teacher}}</td>
			</tr>
		</tbody>
	</table>
	
	<table class="table responsive table-striped table-bordered table-hover">
		<div class="h4 py-2 mx-auto text-center bg-info">
		Marksheet</div>
		<thead>
			<th>Subject ID</th>
			<th>Subject</th>
			<th>Mark</th>
			<th>Grades</th>
			<th>Grade Point</th>
			<th>Remarks</th>
		</thead>
		<tbody>
			{% for marks in studentmarks.all %}
			<tr>
				<td>{{marks.subject.id}}</td>
				<td>{{marks.subject.title}}</td>
				<td>{{marks.marks}}</td>
				<td>{{marks.gradepoint}}</td>
				<td>{{marks.gradeletter}}</td>
				<td>{{marks.remark}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

</div>
{% endblock %}


{% block rightsidebar %}
<div class="h4 py-2 mx-auto text-center bg-info">
	Final Score</div>
<table class="table responsive table-striped table-bordered table-hover js-basic-example dataTable" >
	<thead>
		<tr>
			<th>GPA</th>
			<th>Avg. Grade</th>
			<th>Remarks</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{gpa}}</td>
			<td>{{final_gradeletter}}</td>
			<td>{{final_remark}}</td>
		</tr>
	</tbody>
</table>

<a target="_blank" class='btn btn-success' href="{% url 'schoolapp:generatepdf' %}">Download MarksSheet</a>

{% endblock %}

{% block footer %}
	<div class="h1 mb-0 py-2 bg-dark text-light text-center">Student Detail Footer</div>
{% endblock %}

templates/studentdetailpdf.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<style>
		.table {
			text-align: center;
		}
	</style>
</head>
<body>

<div class="h1 py-3 bg-dark text-light text-center">Student Detail Header</div>

<div class="container-fluid">
	<table class="table responsive table-striped table-bordered table-hover js-basic-example dataTable" >
		<div class="h4 py-2 mx-auto text-center bg-info">
		Details</div>
		<thead>
			<th>Student Id</th>
			<th>Student Name</th>
			<th>Grade</th>
			<th>Class Teacher</th>
		</thead>
		<tbody>
			<tr>
				<td>{{student.id}}</td>
				<td>{{student.name}}</td>
				<td>{{student.grade}}</td>
				<td>{{student.grade.class_teacher}}</td>
			</tr>
		</tbody>
	</table>
	
	<table class="table responsive table-striped table-bordered table-hover js-basic-example dataTable" >
		<div class="h4 py-2 mx-auto text-center bg-info">
		Marksheet</div>
		<thead>
			<th>Subject ID</th>
			<th>Subject</th>
			<th>Mark</th>
			<th>Grades</th>
			<th>Grade Point</th>
			<th>Remarks</th>
		</thead>
		<tbody>
			{% for marks in studentmarks.all %}
			<tr>
				<td>{{marks.subject.id}}</td>
				<td>{{marks.subject.title}}</td>
				<td>{{marks.marks}}</td>
				<td>{{marks.gradepoint}}</td>
				<td>{{marks.gradeletter}}</td>
				<td>{{marks.remark}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

</div>

<div class="h4 py-2 mx-auto text-center bg-info">
	Final Score</div>
<table class="table responsive table-striped table-bordered table-hover js-basic-example dataTable" >
	<thead>
		<tr>
			<th>GPA</th>
			<th>Avg. Grade</th>
			<th>Remarks</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{gpa}}</td>
			<td>{{final_gradeletter}}</td>
			<td>{{final_remark}}</td>
		</tr>
	</tbody>
</table>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>
</body>